import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def src(doc_id, label, file_path, page, location):
    return {
        "docId": doc_id,
        "label": label,
        "file": file_path,
        "page": page,
        "location": location,
    }


STUDY = {
    "T-6B": {
        "aircraft": "T-6B",
        "title": "T-6B Texan II",
        "emergencyProcedures": [
            {
                "id": "t6b-abort-start",
                "title": "Abort Start Procedure",
                "category": "Critical Action",
                "steps": ["PCL - OFF", "STARTER switch - AUTO/RESET"],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 287, "Figure 3-13. Critical Action Table"),
            },
            {
                "id": "t6b-emergency-engine-shutdown-ground",
                "title": "Emergency Engine Shutdown on the Ground",
                "category": "Critical Action",
                "steps": ["PCL - OFF", "FIREWALL SHUTOFF HANDLE - PULL", "Emergency ground egress - As required"],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 287, "Figure 3-13. Critical Action Table"),
            },
            {
                "id": "t6b-emergency-ground-egress",
                "title": "Emergency Ground Egress",
                "category": "Critical Action",
                "steps": [
                    "ISS mode selector - SOLO",
                    "Seat safety pin - Install (BOTH)",
                    "PARKING BRAKE - As required",
                    "Canopy - Open",
                    "CFS handle safety pin - Remove (BOTH)",
                    "CFS handle - Rotate 90 degrees counterclockwise and pull (BOTH)",
                    "Upper fittings, lower fittings, and leg restraint garters - Release (BOTH)",
                    "BAT, GEN, and AUX BAT switches - OFF",
                    "Evacuate aircraft",
                ],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 287, "Figure 3-13. Critical Action Table"),
            },
            {
                "id": "t6b-abort",
                "title": "Abort",
                "category": "Critical Action",
                "steps": ["PCL - IDLE", "BRAKES - AS REQUIRED"],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 287, "Figure 3-13. Critical Action Table"),
            },
            {
                "id": "t6b-engine-failure-immediately-after-takeoff",
                "title": "Engine Failure Immediately After Takeoff",
                "category": "Critical Action",
                "steps": ["EJECT (BOTH)"],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 287, "Figure 3-13. Critical Action Table"),
            },
            {
                "id": "t6b-engine-failure-flight",
                "title": "Engine Failure During Flight",
                "category": "Critical Action",
                "steps": [
                    "ZOOM/GLIDE - 125 KNOTS (MINIMUM)",
                    "PCL - OFF",
                    "INTERCEPT ELP",
                    "Airstart - Attempt if warranted",
                    "FIREWALL SHUTOFF handle - Pull",
                    "Execute Forced Landing or Eject",
                ],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 240, "Engine Failure During Flight"),
            },
            {
                "id": "t6b-immediate-airstart-pmu-norm",
                "title": "Immediate Airstart (PMU NORM)",
                "category": "Critical Action",
                "steps": [
                    "ZOOM/GLIDE - 125 KNOTS (MINIMUM)",
                    "PCL - OFF",
                    "PCL - IDLE, ABOVE 13% N1",
                    "Engine instruments - Monitor ITT, N1, and oil pressure",
                    "PCL - OFF",
                    "FIREWALL SHUTOFF handle - Pull",
                    "Execute Forced Landing or Eject",
                    "PCL - As required after N1 reaches IDLE RPM (approximately 67% N1)",
                    "PEL - Execute",
                ],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 288, "Immediate Airstart (PMU NORM)"),
            },
            {
                "id": "t6b-uncommanded-power-change",
                "title": "Uncommanded Power Changes / Loss of Power / Uncommanded Propeller Feather",
                "category": "Critical Action",
                "steps": [
                    "PCL - MID RANGE",
                    "PMU SWITCH - OFF",
                    "PROP SYS CIRCUIT BREAKER - PULL, IF NP STABLE BELOW 40%",
                    "PCL - As required",
                    "PEL - Execute",
                    "PROP SYS circuit breaker - Reset, as required",
                    "PCL - OFF",
                    "FIREWALL SHUTOFF handle - Pull",
                    "Execute Forced Landing or Eject",
                ],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 288, "Uncommanded Power Changes / Loss of Power / Uncommanded Propeller Feather"),
            },
            {
                "id": "t6b-compressor-stalls",
                "title": "Compressor Stalls",
                "category": "Critical Action",
                "steps": ["PCL - IDLE", "PMU switch - OFF", "Land as soon as possible"],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 288, "Compressor Stalls"),
            },
            {
                "id": "t6b-ocf",
                "title": "Inadvertent Departure From Controlled Flight",
                "category": "Critical Action",
                "steps": ["PCL - IDLE", "CONTROLS - NEUTRAL", "ALTITUDE - CHECK", "Recover from unusual attitude"],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 289, "Inadvertent Departure From Controlled Flight"),
            },
            {
                "id": "t6b-fire-in-flight",
                "title": "Fire In Flight",
                "category": "Critical Action",
                "steps": ["PCL - OFF", "FIREWALL SHUTOFF HANDLE - PULL", "Forced Landing - Execute", "Eject (BOTH)", "PEL - Execute"],
                "note": "If fire is not confirmed, execute PEL. If fire is extinguished, execute a forced landing.",
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 247, "Fire In Flight"),
            },
            {
                "id": "t6b-smoke-fume-electrical-fire",
                "title": "Smoke and Fume Elimination / Electrical Fire",
                "category": "Emergency Procedure",
                "steps": [
                    "OBOGS - CHECK (BOTH): supply lever ON, concentration lever MAX, pressure lever EMERGENCY",
                    "Descend below 10,000 feet MSL - Initiate (as required)",
                    "PRESSURIZATION switch - RAM/DUMP",
                    "BLEED AIR INFLOW switch - OFF",
                    "BAT and GEN switches - OFF",
                    "AUX BAT switch - OFF (as required)",
                    "CFS handle safety pin - Remove (BOTH)",
                    "CFS - Rotate 90 degrees counterclockwise and pull (if necessary)",
                    "Restore electrical power - As required",
                    "Land as soon as possible",
                ],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 248, "Smoke and Fume Elimination / Electrical Fire"),
            },
            {
                "id": "t6b-chip-detector",
                "title": "Chip Detector Warning",
                "category": "Critical Action",
                "steps": ["PCL - Minimum necessary to intercept ELP; avoid unnecessary PCL movements", "PEL - Execute"],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 289, "Chip Detector Warning"),
            },
            {
                "id": "t6b-oil-system",
                "title": "Oil System Malfunction or Low Oil Pressure",
                "category": "Critical Action",
                "steps": ["Terminate maneuver", "Check oil pressure", "Land as soon as possible"],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 289, "Oil System Malfunction or Low Oil Pressure"),
            },
            {
                "id": "t6b-obogs-failure",
                "title": "OBOGS Failure / Overtemp / Physiological Symptoms",
                "category": "Critical Action",
                "steps": ["GREEN RING - PULL (AS REQUIRED) (BOTH)", "DESCENT BELOW 10,000 FEET MSL - INITIATE", "OBOGS SUPPLY LEVER - OFF (BOTH)"],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 290, "Figure 3-13. Critical Action Table"),
            },
            {
                "id": "t6b-eject",
                "title": "Eject",
                "category": "Critical Action",
                "steps": ["EJECTION HANDLE - PULL (BOTH)"],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 290, "Figure 3-13. Critical Action Table"),
            },
            {
                "id": "t6b-forced-landing",
                "title": "Forced Landing",
                "category": "Critical Action",
                "steps": [
                    "Airspeed - 125 KIAS prior to extending landing gear",
                    "EMER LDG GR handle - Pull (as required)",
                    "Airspeed - 120 KIAS minimum until intercepting final; 110 KIAS minimum on final",
                    "Flaps - As required",
                ],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 290, "Figure 3-13. Critical Action Table"),
            },
            {
                "id": "t6b-pel",
                "title": "Precautionary Emergency Landing (PEL)",
                "category": "Critical Action",
                "steps": ["Turn to nearest suitable field", "Climb or accelerate to intercept ELP", "Gear, flaps, speed brake - UP"],
                "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 290, "Figure 3-13. Critical Action Table"),
            },
        ],
        "limits": [
            {"id": "t6b-vmo-mmo", "label": "VMO / MMO", "value": "316 KIAS up to and including 19,020 feet MSL; 0.67 IMN above 19,020 feet MSL.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 300, "Maximum Operating Airspeed / Maximum Operating Mach Number")},
            {"id": "t6b-vfe", "label": "Flaps Limit", "value": "VFE is 150 KIAS.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 300, "Wing Flaps Limitations")},
            {"id": "t6b-vle", "label": "Landing Gear Limit", "value": "VLE is 150 KIAS.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 300, "Landing Gear Limitations")},
            {"id": "t6b-vg", "label": "Turbulent Air", "value": "VG is 207 KIAS; recommended turbulent airspeed is 180 KIAS.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 300, "Turbulent Air Penetration Speed Limitations")},
            {"id": "t6b-vo", "label": "Operating Maneuvering Speed", "value": "VO is 227 KIAS; full rudder deflection above 150 KIAS exceeds rudder control system limits.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 300, "Maneuvering Speed Limitations")},
            {"id": "t6b-zero-g", "label": "Zero G Limit", "value": "Zero G is limited to 5 seconds maximum.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 301, "Flight Maneuvering Limitations")},
            {"id": "t6b-negative-g", "label": "Negative G Limits", "value": "Negative G operation, including inverted, is limited to 60 seconds. Additional negative G maneuvers require 60 seconds upright flight between maneuvers.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 301, "Flight Maneuvering Limitations")},
            {"id": "t6b-prohibited", "label": "Prohibited Maneuvers", "value": "Inverted stalls, inverted spins, aggravated spins past two turns, spins with PCL above idle, spins with landing gear, flaps, or speed brake extended, spins with PMU off, and spins below 10,000 feet pressure altitude are prohibited.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 301, "Prohibited Maneuvers")},
            {"id": "t6b-weights", "label": "Weight Limits", "value": "Maximum ramp 6,950 pounds; takeoff 6,900 pounds; landing 6,900 pounds; zero fuel 5,850 pounds; baggage compartment 80 pounds.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 302, "Weight Limitations")},
            {"id": "t6b-touchdown-rate", "label": "Touchdown Sink Rate", "value": "600 feet per minute at normal landing tire pressure; 780 feet per minute at maximum landing tire pressure.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 302, "Landing Limitations")},
            {"id": "t6b-wind", "label": "Wind Limits", "value": "Maximum crosswind component: dry runway 25 knots, wet runway 10 knots, icy runway 5 knots. Maximum tailwind component for takeoff: 10 knots.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 302, "Wind Limitations")},
            {"id": "t6b-fuel-imbalance", "label": "Fuel Imbalance", "value": "Maximum lateral fuel imbalance is 50 pounds.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 305, "Fuel Imbalance")},
            {"id": "t6b-temp", "label": "Ground Temperature Limits", "value": "Ground operation is limited to ambient temperatures from -23 C to +43 C. Ground operation above +43 C is permitted for up to 15 minutes only to taxi the aircraft to park.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 305, "Temperature Limitations")},
            {"id": "t6b-generator", "label": "Generator Limits", "value": "Inflight generator limits: +50 to -2 AMPS. Ground / inflight voltage: 28.0 to 28.5 volts.", "source": src("a1-t6baa-nfm-000", "NATOPS", "t6b/A1-T6BAA-NFM-000.pdf", 299, "Generator Limitations")},
        ],
    },
    "T-44C": {
        "aircraft": "T-44C",
        "title": "T-44C Pegasus",
        "emergencyProcedures": [
            {"id": "t44c-abnormal-start", "title": "Abnormal Start", "category": "Critical Action", "steps": ["CONDITION LEVER - FUEL CUTOFF (DEC BELOW 790 C)", "STARTER - STARTER ONLY (FOR THE REMAINDER OF THE 40 SECONDS)", "STARTER - OFF (AT 40 SECONDS)"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Abnormal Start")},
            {"id": "t44c-smoke-fume-elimination", "title": "Smoke and Fume Elimination", "category": "Critical Action", "steps": ["OXYGEN MASK / MIC SWITCHES (100 PERCENT) - AS REQUIRED", "PRESSURIZATION - DUMP"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Smoke and Fume Elimination")},
            {"id": "t44c-fuel-leaks", "title": "Fuel Leaks", "category": "Critical Action", "steps": ["CONDITION LEVER - FUEL CUTOFF", "EMERGENCY SHUTDOWN CHECKLIST - EXECUTE"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Fuel Leaks")},
            {"id": "t44c-emergency-shutdown-deck", "title": "Emergency Shutdown on Deck", "category": "Critical Action", "steps": ["STOP THE AIRCRAFT AND SET THE PARKING BRAKE", "CONDITION LEVER(S) - FUEL CUTOFF", "FIREWALL VALVES - CLOSED", "BOOST PUMPS - OFF", "FIRE EXTINGUISHER - AS REQUIRED", "AUX BATT SWITCH - OFF", "GANGBAR - OFF", "EVACUATE AIRCRAFT"], "source": src("natops-checklist-01-t44aac-1c", "Checklist", "t44c/NATOPS Checklist-01-T44AAC-1C.pdf", 2, "Emergency Shutdown on Deck")},
            {"id": "t44c-aborting-takeoff", "title": "Aborting Takeoff", "category": "Critical Action", "steps": ["ANNOUNCE \"ABORT\"", "POWER LEVERS - IDLE", "REVERSE - AS REQUIRED", "BRAKES - AS REQUIRED", "CONDITION LEVERS - FUEL CUTOFF", "FIREWALL VALVES - CLOSED", "BOOST PUMPS - OFF", "FIRE EXTINGUISHER(S) - AS REQUIRED", "AUX BATT SWITCH - OFF", "GANGBAR - OFF", "EVACUATE AIRCRAFT"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Aborting Takeoff")},
            {"id": "t44c-engine-failure-after-takeoff", "title": "Engine Failure After Takeoff", "category": "Critical Action", "steps": ["POWER - AS REQUIRED", "LANDING GEAR - UP", "AIRSPEED - AS REQUIRED (VXSE OR VYSE)", "EMERGENCY SHUTDOWN CHECKLIST - EXECUTE"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Engine Failure After Takeoff")},
            {"id": "t44c-emergency-shutdown-checklist", "title": "Emergency Shutdown Checklist", "category": "Critical Action", "steps": ["POWER LEVER - IDLE", "PROP LEVER - FEATHER", "CONDITION LEVER - FUEL CUTOFF", "FIREWALL VALVE - CLOSED", "FIRE EXTINGUISHER - AS REQUIRED", "BLEED AIR VALVE - CLOSED"], "source": src("natops-checklist-01-t44aac-1c", "Checklist", "t44c/NATOPS Checklist-01-T44AAC-1C.pdf", 2, "Emergency Shutdown Checklist")},
            {"id": "t44c-windmilling-airstart", "title": "Windmilling Airstart", "category": "Critical Action", "steps": ["POWER LEVER (FAILED ENGINE) - IDLE", "PROP LEVER (FAILED ENGINE) - FULL FORWARD", "CONDITION LEVER (FAILED ENGINE) - FUEL CUTOFF", "FIREWALL VALVE - OPEN", "AUTOIGNITION - ARMED", "CONDITION LEVER - LOW IDLE", "POWER - AS REQUIRED"], "source": src("natops-checklist-01-t44aac-1c", "Checklist", "t44c/NATOPS Checklist-01-T44AAC-1C.pdf", 2, "Windmilling Airstart")},
            {"id": "t44c-primary-governor", "title": "Primary Governor Failure / Malfunction", "category": "Critical Action", "steps": ["ATTEMPT TO ADJUST PROP RPM TO NORMAL OPERATING RANGE", "POWER LEVER - IDLE", "PROP LEVER - FEATHER", "ALTERNATE PROP FEATHER CHECKLIST - AS REQUIRED", "LAND AS SOON AS POSSIBLE"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Primary Governor Failure / Malfunction")},
            {"id": "t44c-explosive-decompression", "title": "Explosive Decompression", "category": "Critical Action", "steps": ["OXYGEN MASK / MIC SWITCHES (100 PERCENT) - AS REQUIRED", "DESCEND - AS REQUIRED"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Explosive Decompression")},
            {"id": "t44c-unscheduled-electric-trim", "title": "Unscheduled Electric Trim Activation", "category": "Critical Action", "steps": ["A/P / TRIM DISCONNECT (control wheel) - DEPRESS FULLY AND HOLD"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Unscheduled Electric Trim Activation")},
            {"id": "t44c-emergency-descent", "title": "Emergency Descent Procedure", "category": "Critical Action", "steps": ["POWER LEVERS - IDLE", "PROPS - FULL FORWARD", "FLAPS - AS REQUIRED", "LANDING GEAR - AS REQUIRED", "AIRSPEED - AS REQUIRED", "WINDSHIELD HEAT - AS REQUIRED"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Emergency Descent Procedure")},
            {"id": "t44c-spin-recovery", "title": "Spin / Out of Control Flight Recovery", "category": "Critical Action", "steps": ["POWER LEVERS - IDLE", "RUDDER - FULL DEFLECTION OPPOSITE DIRECTION OF TURN NEEDLE", "CONTROL WHEEL - RAPIDLY FORWARD", "RUDDER - NEUTRALIZE AFTER ROTATION STOPS", "CONTROL WHEEL - PULL OUT OF DIVE BY EXERTING SMOOTH, STEADY BACK PRESSURE"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Spin / Out of Control Flight Recovery")},
            {"id": "t44c-terrain-warning", "title": "Terrain Warning (IMC or at Night)", "category": "Critical Action", "steps": ["WINGS - LEVEL", "POWER - MAX CONTINUOUS", "PITCH - AS REQUIRED TO SET AND MAINTAIN VX", "FLAPS - APPROACH (UNLESS ALREADY UP)", "GEAR - UP", "FLAPS - UP", "PROPS - 1900 RPM", "CONTINUE CLIMB AT VX UNTIL ALL VISUAL AND VOICE WARNINGS CEASE"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Terrain Warning (IMC or at Night)")},
            {"id": "t44c-single-engine-waveoff", "title": "Single-Engine Waveoff / Missed Approach", "category": "Critical Action", "steps": ["POWER - MAX CONTINUOUS, ESTABLISH POSITIVE RATE OF CLIMB (VXSE MINIMUM)", "FLAPS - APPROACH (UNLESS ALREADY UP)", "LANDING GEAR - UP", "FLAPS - UP", "PROP - 1900 RPM"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Single-Engine Waveoff / Missed Approach")},
            {"id": "t44c-low-altitude-windshear", "title": "Low Altitude Windshear", "category": "Critical Action", "steps": ["POWER - MAXIMUM CONTINUOUS", "PITCH - SET AND HOLD APPROXIMATELY 15 DEGREES NOSEUP", "LANDING GEAR - UP", "FLAPS - MAINTAIN CURRENT SETTING"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Low Altitude Windshear")},
            {"id": "t44c-waveoff-missed-approach", "title": "Waveoff / Missed Approach", "category": "Critical Action", "steps": ["POWER - AS REQUIRED, ESTABLISH POSITIVE RATE OF CLIMB (VX MINIMUM)", "FLAPS - APPROACH (UNLESS ALREADY UP)", "LANDING GEAR - UP", "FLAPS - UP", "PROPS - 1900 RPM"], "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 1, "Waveoff / Missed Approach")},
            {"id": "t44c-smoke-fire-unknown", "title": "Smoke / Fire of Unknown Origin", "category": "Emergency Procedure", "steps": ["CREW - ALERTED", "CABIN TEMPERATURE MODE - OFF", "VENT BLOWER - AUTO", "OXYGEN MASKS / MIC SWITCHES (100%) - AS REQUIRED", "BLEED AIR VALVES - CLOSED", "EMERGENCY DESCENT - AS REQUIRED", "PRESSURIZATION - DUMP", "EMERGENCY TRANSMISSION - AS REQUIRED", "GANGBAR - OFF", "ALL ELECTRICAL SWITCHES (EXCEPT AUX BATT) - OFF", "BATTERY - ON", "GENERATORS (ONE AT A TIME) - ON", "ESSENTIAL EQUIPMENT - ON"], "source": src("natops-checklist-01-t44aac-1c", "Checklist", "t44c/NATOPS Checklist-01-T44AAC-1C.pdf", 2, "Smoke / Fire of Unknown Origin")},
        ],
        "limits": [
            {"id": "t44c-engine-limits", "label": "Engine Operating Limits", "value": "Maximum allowable 5 minutes: 1,315 ft-lb torque at 2,200 RPM or 1,520 ft-lb at 1,900 RPM, ITT 790, N1 101.5%, prop 2,200 RPM, oil pressure 85-100 PSI, oil temp 10-99 C.", "source": src("a1-t44ca-nfm-000", "NATOPS", "t44c/A1-T44CA-NFM-000.pdf", 198, "Figure 4.3-1. Engine Operating Limitations")},
            {"id": "t44c-fuel-capacity", "label": "Fuel Capacity", "value": "Total fuel capacity is 387.6 U.S. gallons, of which 384 U.S. gallons are usable.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "Fuel System Capacity")},
            {"id": "t44c-normal-tas-range", "label": "Normal TAS Altitude Range", "value": "Plus or minus 2,700 feet, flared landings only.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "General Limitations")},
            {"id": "t44c-altitude", "label": "Altitude Ceiling", "value": "31,000 feet.", "source": src("a1-t44ca-nfm-000", "NATOPS", "t44c/A1-T44CA-NFM-000.pdf", 201, "Altitude Limitations")},
            {"id": "t44c-touchdown", "label": "Touchdown Sink Rate", "value": "Maximum sink rate at ground contact is 600 feet per minute.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "General Limitations")},
            {"id": "t44c-crosswind", "label": "Crosswind Limit", "value": "Maximum crosswind component is 20 knots.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "General Limitations")},
            {"id": "t44c-gyro-suction", "label": "Gyro Suction", "value": "Normal operating range is 4.3 to 5.9 inHg.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "General Limitations")},
            {"id": "t44c-min-oxygen", "label": "Minimum Oxygen Required", "value": "Local / cross-country flight minimum oxygen is 1,000 / 1,500 PSI.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "General Limitations")},
            {"id": "t44c-cabin", "label": "Cabin Pressure Differential", "value": "Maximum operating cabin pressure differential is 4.7 PSI.", "source": src("a1-t44ca-nfm-000", "NATOPS", "t44c/A1-T44CA-NFM-000.pdf", 202, "Structural Limitations")},
            {"id": "t44c-vmcg", "label": "VMCG", "value": "Minimum controllable speed on ground is 63 KIAS.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "Landing Limitations")},
            {"id": "t44c-flap-g", "label": "Flap G Limits", "value": "Full flaps: +2.0 to 0.0 G.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "Landing Limitations")},
            {"id": "t44c-pneumatic", "label": "Pneumatic Pressure", "value": "Normal operating range is 12 to 20 PSI.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "General Limitations")},
            {"id": "t44c-weights", "label": "Weight Limits", "value": "Maximum ramp 9,710 pounds; maximum takeoff 9,650 pounds; maximum landing 9,168 pounds.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "Weight Limitations")},
            {"id": "t44c-vspeeds", "label": "Climb and Glide Speeds", "value": "VYSE 110 KIAS, max range glide 130 KIAS, max endurance glide 102 KIAS, VX 102 KIAS, VY 108 KIAS, VXSE 102 KIAS.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "General Limitations")},
            {"id": "t44c-gear-flap", "label": "Gear and Flap Limits", "value": "VLE 155 KIAS. Landing gear retraction 145 KIAS. VFE approach 174 KIAS. VFE full 140 KIAS.", "source": src("a1-t44ca-nfm-000", "NATOPS", "t44c/A1-T44CA-NFM-000.pdf", 201, "Airframe Limitations")},
            {"id": "t44c-engine-safe-speeds", "label": "Single-Engine and Maneuvering Speeds", "value": "VSSE 91 KIAS, VMCA 86 KIAS, VA 153 KIAS.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "Airspeed Limitations")},
            {"id": "t44c-vmo", "label": "VMO / MMO", "value": "VMO is 227 KIAS. Decrease VMO 4 KIAS for every 1,000 feet above 15,500 feet. MMO is 0.48 Mach.", "source": src("a1-t44ca-nfm-000", "NATOPS", "t44c/A1-T44CA-NFM-000.pdf", 201, "Airframe Limitations")},
            {"id": "t44c-battery", "label": "Battery Voltage Minimums", "value": "Minimum battery voltage for APU charge is 18 VDC, APU start is 20 VDC, and battery start is 22 VDC.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "Electrical Limitations")},
            {"id": "t44c-starter-cycle", "label": "Starter Cycle Limits", "value": "Starter duty cycle is limited to three 40-second cycles. Cooling periods: first cycle 60 seconds, second cycle 60 seconds, third cycle 30 minutes.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "Starter Cycle Limitations")},
            {"id": "t44c-prop-deicer", "label": "Prop Deicer Ammeter", "value": "Normal operation is 14 to 18 amps.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "General Limitations")},
            {"id": "t44c-acceleration", "label": "Acceleration Limits", "value": "Clean: +3.0 to -1.0 G.", "source": src("a1-t44ca-nfm-000", "NATOPS", "t44c/A1-T44CA-NFM-000.pdf", 201, "Acceleration Limitations")},
            {"id": "t44c-prohibited", "label": "Prohibited Maneuvers", "value": "Intentional spins are prohibited.", "source": src("t44c-ops-limits-answers", "Ops Limits Study Sheet", "t44c/t44c-ops-limits-answers.pdf", 2, "Prohibited Maneuvers")},
        ],
    },
    "T-45C": {
        "aircraft": "T-45C",
        "title": "T-45C Goshawk",
        "emergencyProcedures": [
            {"id": "t45c-loss-directional-control", "title": "Loss of Directional Control", "category": "Critical Action", "steps": ["Go-around", "Paddle switch - PRESS", "Gear and flaps - DO NOT REPOSITION", "Engine instruments - MONITOR", "Refer to procedure for blown tire(s) or NWS / NWS AUG caution light"], "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 499, "13.4 Loss of Directional Control")},
            {"id": "t45c-abort", "title": "Abort", "category": "Critical Action", "steps": ["Throttle - IDLE", "Speed brakes - EXTEND", "Brakes - APPLY", "Hook - DOWN (IF REQUIRED)"], "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 501, "14.1 Abort")},
            {"id": "t45c-fuel-leak", "title": "Fuel Leak / Excessive Fuel Flow", "category": "Emergency Procedure", "steps": ["Throttle - AS REQUIRED (maintain a minimum of 70 percent N2)", "Land as soon as possible"], "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 521, "15.6 Fuel Leak / Excessive Fuel Flow")},
            {"id": "t45c-vibrations", "title": "Vibrations", "category": "Emergency Procedure", "steps": ["Throttle - MINIMUM FOR SAFE FLIGHT", "Engine instruments - MONITOR", "Altitude - DESCEND BELOW 10,000 FEET IF POSSIBLE", "AIR FLOW knob - OFF", "Reduce airspeed", "AIR FLOW knob - NORMAL / AS DESIRED", "Request inspection by other aircraft, if practical", "Land as soon as possible"], "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 523, "15.7 Vibrations")},
            {"id": "t45c-electrical-fire", "title": "Electrical Fire", "category": "Critical Action", "steps": ["GEN switch - OFF", "Non-essential electrical equipment - OFF", "Land as soon as practicable", "Proceed to VMC as soon as possible", "BATT switches - OFF", "Emergency oxygen green ring(s) - PULL", "Land as soon as possible", "Landing gear - EMERGENCY EXTEND", "Plan a no-flap approach and arrested landing, if available"], "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 525, "15.8 Electrical Fire")},
            {"id": "t45c-smoke-fumes", "title": "Smoke or Fumes in Cockpit", "category": "Critical Action", "steps": ["Mask - ON / TIGHT", "Initiate controlled descent to below 18,000 feet MSL", "AIR FLOW knob - OFF (below 18,000 feet MSL if possible)", "Airspeed - REDUCE (as practical)", "Warn other cockpit occupant / secure loose items", "Seat - LOWER", "MDC firing handle - PULL", "Land as soon as possible"], "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 527, "15.9 Smoke or Fumes in Cockpit")},
            {"id": "t45c-rapid-decompression", "title": "Rapid Decompression", "category": "Critical Action", "steps": ["Emergency oxygen green ring(s) - PULL", "OBOGS FLOW selector(s) - OFF", "Descend below 10,000 feet cabin altitude", "Remain on emergency oxygen until depleted and then resume OBOGS operation until engine shutdown", "Land as soon as practicable"], "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 529, "15.10 Rapid Decompression")},
            {"id": "t45c-total-electrical-failure", "title": "Total Electrical Failure", "category": "Critical Action", "steps": ["Emergency oxygen green ring(s) - PULL", "Proceed to VMC as soon as possible", "Attempt to reset generator / check BATT switches - ON", "Land as soon as practicable", "Landing gear - EMERGENCY EXTEND", "Plan a no-flap / slat approach", "Make a short field arrestment if available"], "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 535, "15.13 Total Electrical Failure")},
        ],
        "limits": [
            {"id": "t45c-solo", "label": "Solo Flying", "value": "Solo flying shall be conducted only from the forward cockpit.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 311, "4.1.1 Solo Flying")},
            {"id": "t45c-altitude", "label": "Altitude Limit", "value": "Maximum altitude is 41,000 feet MSL.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 311, "4.1.2 Altitude Limits")},
            {"id": "t45c-icing", "label": "Icing", "value": "Flight in known icing conditions shall be avoided. When airframe icing is visible, intentional stalls or use of full flaps is not authorized.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 311, "4.1.3 Icing")},
            {"id": "t45c-engine-handling", "label": "Engine Handling Limits", "value": "Throttle shall be at idle for abrupt pulls to full back stick, abrupt full lateral stick inputs at full back stick, and airspeeds less than 85 KIAS above 15,000 feet MSL.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 313, "4.2.1 Engine Handling Limitations")},
            {"id": "t45c-engine", "label": "Engine Operating Limits", "value": "MRT: 104 percent N2 / 610 C for 30 minutes per flight hour. Transient: 106 percent N2 / 645 C for less than 20 seconds. Maximum continuous: 100 percent N2 / 550 C. Idle: 56.5 +/- 2 percent N2 / 450 C.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 314, "Figure 4.2-1. F405-RR-401 Operating Limitations")},
            {"id": "t45c-gts", "label": "GTS Start Limits", "value": "GTS start with external power is prohibited. Minimum interval between each GTS start attempt is 3 minutes. After three consecutive starts, wait 30 minutes before any further start attempts.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 317, "4.3 GTS Limitations")},
            {"id": "t45c-fuel-temp", "label": "Fuel Temperature Limits", "value": "For A++(F-24), Jet A, and A++100 (F-27), do not allow indicated TAT to dwell at or below the fuel freeze point plus 3 C. Operation is restricted to ambient temperatures above 0 C when using fuel without FSII.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 319, "4.4 Fuel Limitations")},
            {"id": "t45c-system-speeds", "label": "System Airspeed Limits", "value": "Landing gear transition / extended: 200 KIAS or less. Flaps / slats transition / extended: 200 KIAS or less. Arresting hook transition / extended: 450 KIAS or less.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 322, "Figure 4.5-2. System Operation Limitations")},
            {"id": "t45c-canopy-deck", "label": "Canopy and Deck Limits", "value": "Canopy full open for taxi: prevailing wind 20 knots or less. Stationary or towing with canopy full open: prevailing wind 32 knots or less. Tires and nosewheel steering on deck: 176 knots groundspeed or less.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 322, "Figure 4.5-2. System Operation Limitations")},
            {"id": "t45c-hot-refuel", "label": "Hot Refueling", "value": "Hot refueling fuel level must be 2,800 pounds or less if PRECHECK is unsuccessful.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 322, "Figure 4.5-2. System Operation Limitations")},
            {"id": "t45c-crosswind", "label": "Crosswind Limits", "value": "Single aircraft dry runway 20 knots, wet runway 15 knots, section takeoff 10 knots, banner tow 10 knots, NWS off / failed 15 knots.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 323, "4.5.5 Takeoff / Landing Limitations")},
            {"id": "t45c-high-gain-nws", "label": "High Gain Nosewheel Steering", "value": "High gain nosewheel steering shall be used for low speed taxi operations only, less than 10 knots groundspeed.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 323, "4.5.5 Takeoff / Landing Limitations")},
            {"id": "t45c-fclp", "label": "FCLP Landing Configurations", "value": "FCLP landings are authorized only with clean loading and full flaps, or pylons alone / pylons with empty PMBRs or BRU-38A and full flaps.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 323, "4.5.5 Takeoff / Landing Limitations")},
            {"id": "t45c-landing-sink", "label": "Landing Sink Rate", "value": "For landings in a configuration other than authorized FCLP configurations, sink rate shall not exceed 600 feet per minute.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 323, "4.5.5 Takeoff / Landing Limitations")},
            {"id": "t45c-banner", "label": "Banner Tow Limits", "value": "Maximum altitude 20,000 feet MSL. Maximum airspeed 220 KIAS. Maximum bank angle 45 degrees. Maximum AOA 18 units.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 324, "4.5.6 Banner Towing")},
            {"id": "t45c-banner-release", "label": "Banner Release Limits", "value": "Minimum banner release altitude 500 feet AGL. Banner release airspeed 140 to 200 KIAS. For release between 140 and 150 KIAS, use one-half flaps.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 324, "4.5.6 Banner Towing")},
            {"id": "t45c-prohibited", "label": "Prohibited Maneuvers", "value": "Intentional spins or tailslides are prohibited. Sustained zero or negative G flight for more than 30 seconds is prohibited.", "source": src("a1-t45ca-nfm-000", "NATOPS", "t45c/A1-T45CA-NFM-000.pdf", 324, "4.5.7 Prohibited Maneuvers")},
        ],
    },
}


def main():
    for aircraft, key in (("T-6B", "t6b"), ("T-44C", "t44c"), ("T-45C", "t45c")):
        target = ROOT / "data" / key / "study-data.json"
        target.write_text(json.dumps(STUDY[aircraft], indent=2) + "\n", encoding="utf-8")

    (ROOT / "data" / "study-data.json").write_text(json.dumps(STUDY, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
